apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jobstream
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/DjarallahBrahim/jobOffer-helm
    path: jobstream
    targetRevision: HEAD
    helm:
      releaseName: jobstream
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true


